# App
spring.application.name=FinanzAPP

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finanzasdb
spring.datasource.username=postgres
spring.datasource.password=juanjose780x
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto
server.port=${PORT:8080}

# JWT
jwt.secret=cGFsYWJyYVNlY3JldGFNdXlMYXJnYVBhcmFFbFByb3llY3RvRmluYW56QVBQ
jwt.expiration=86400000

# Email (Gmail - cambiar con datos reales)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=juanjo222e@gmail.com------------
#spring.mail.password=tu_password_de_aplicacion----------
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
spring.web.cors.allowed-origins=http://localhost:5173
